import '../models/movie.dart';

class OfflineMoviesData {
  static final List<Movie> sampleMovies = [
    Movie(
      id: 1001,
      slug: 'stree-2-2024-hindi',
      title: 'Stree 2: Sarkate Ka Aatank',
      rawTitle: 'Stree 2 (2024) Hindi 480p | 720p | 1080p HQ HDRip Full Movie',
      year: '2024',
      rating: '7.8',
      languages: ['Hindi'],
      qualities: ['480P', '720P', '1080P', '4K'],
      size: '1.2 GB',
      storyline:
          'After the events of Stree, the town of Chanderi is being haunted by a new headless monster named Sarkata who abducts modern independent women. Vicky and his friends must team up once again to save their town.',
      poster: 'https://m.media-amazon.com/images/M/MV5BMjA4NzUyNWEtZTI0Mi00MThhLThlYjktYzA1Y2VjYmFiY2I5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      screenshots: [
        'https://m.media-amazon.com/images/M/MV5BMjA4NzUyNWEtZTI0Mi00MThhLThlYjktYzA1Y2VjYmFiY2I5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ],
      categories: [
        const MovieCategory(id: 3, name: 'Bollywood', slug: 'bollywood'),
        const MovieCategory(id: 10, name: 'Hindi', slug: 'hindi'),
        const MovieCategory(id: 0, name: 'Comedy', slug: 'comedy'),
        const MovieCategory(id: 0, name: 'Horror', slug: 'horror'),
      ],
      downloadLinks: [
        DownloadLink(
          title: 'Download 480p [450MB] - Direct Cloud',
          url: 'https://hubcloud.club/drive/stree2-480p-hindi',
          quality: '480P',
          size: '450MB',
        ),
        DownloadLink(
          title: 'Download 720p HEVC [950MB] - Fast Server',
          url: 'https://hubcloud.club/drive/stree2-720p-hevc',
          quality: '720P',
          size: '950MB',
        ),
        DownloadLink(
          title: 'Download 1080p FHD [2.1GB] - Ultra HD',
          url: 'https://hubcloud.club/drive/stree2-1080p-fhd',
          quality: '1080P',
          size: '2.1GB',
        ),
      ],
      date: '2024-08-16T12:00:00',
    ),
    Movie(
      id: 1002,
      slug: 'kalki-2898-ad-2024',
      title: 'Kalki 2898 AD',
      rawTitle: 'Kalki 2898 AD (2024) Multi Audio Hindi + Telugu 480p 720p 1080p WEB-DL',
      year: '2024',
      rating: '7.6',
      languages: ['Hindi', 'Telugu', 'Tamil', 'English'],
      qualities: ['480P', '720P', '1080P', '4K'],
      size: '1.8 GB',
      storyline:
          'Set in a post-apocalyptic world in the year 2898 AD, a modern avatar of Vishnu descends to Earth to protect the world from evil forces in the city of Kasi.',
      poster: 'https://m.media-amazon.com/images/M/MV5BZGQ1NWFiZjEtYTI2MS00N2Y3LTkzMDAtODExYzQ3ZDQ3YWFjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      screenshots: [
        'https://m.media-amazon.com/images/M/MV5BZGQ1NWFiZjEtYTI2MS00N2Y3LTkzMDAtODExYzQ3ZDQ3YWFjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ],
      categories: [
        const MovieCategory(id: 5, name: 'South Indian', slug: 'south-indian'),
        const MovieCategory(id: 1, name: 'Dual Audio', slug: 'dual-audio'),
        const MovieCategory(id: 0, name: 'Action', slug: 'action'),
        const MovieCategory(id: 0, name: 'Sci-Fi & Fantasy', slug: 'sci-fi-fantasy'),
      ],
      downloadLinks: [
        DownloadLink(
          title: 'Download 480p [550MB] - Direct Cloud',
          url: 'https://hubcloud.club/drive/kalki-480p-multi',
          quality: '480P',
          size: '550MB',
        ),
        DownloadLink(
          title: 'Download 720p [1.3GB] - Fast Server',
          url: 'https://hubcloud.club/drive/kalki-720p-multi',
          quality: '720P',
          size: '1.3GB',
        ),
        DownloadLink(
          title: 'Download 1080p [2.8GB] - Ultra HD',
          url: 'https://hubcloud.club/drive/kalki-1080p-multi',
          quality: '1080P',
          size: '2.8GB',
        ),
      ],
      date: '2024-07-28T14:30:00',
    ),
    Movie(
      id: 1003,
      slug: 'deadpool-and-wolverine-2024',
      title: 'Deadpool & Wolverine',
      rawTitle: 'Deadpool and Wolverine (2024) Dual Audio [Hindi-English] 720p 1080p WEB-DL',
      year: '2024',
      rating: '8.0',
      languages: ['Hindi', 'English'],
      qualities: ['720P', '1080P', '4K'],
      size: '1.5 GB',
      storyline:
          'Wade Wilson’s peaceful life is shattered when the Time Variance Authority recruits him to help safeguard the multiverse alongside a reluctant Wolverine.',
      poster: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
      screenshots: [
        'https://image.tmdb.org/t/p/w780/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
      ],
      categories: [
        const MovieCategory(id: 4, name: 'Hollywood', slug: 'hollywood'),
        const MovieCategory(id: 1, name: 'Dual Audio', slug: 'dual-audio'),
        const MovieCategory(id: 0, name: 'Action', slug: 'action'),
        const MovieCategory(id: 0, name: 'Comedy', slug: 'comedy'),
      ],
      downloadLinks: [
        DownloadLink(
          title: 'Download 480p [480MB] - Direct Cloud',
          url: 'https://hubcloud.club/drive/dp-wolverine-480p',
          quality: '480P',
          size: '480MB',
        ),
        DownloadLink(
          title: 'Download 720p [1.1GB] - Fast Server',
          url: 'https://hubcloud.club/drive/dp-wolverine-720p',
          quality: '720P',
          size: '1.1GB',
        ),
        DownloadLink(
          title: 'Download 1080p [2.4GB] - Ultra HD',
          url: 'https://hubcloud.club/drive/dp-wolverine-1080p',
          quality: '1080P',
          size: '2.4GB',
        ),
      ],
      date: '2024-07-26T10:15:00',
    ),
    Movie(
      id: 1004,
      slug: 'fighter-2024-hindi',
      title: 'Fighter',
      rawTitle: 'Fighter (2024) Hindi 480p | 720p | 1080p HDRip Full Movie',
      year: '2024',
      rating: '7.0',
      languages: ['Hindi'],
      qualities: ['480P', '720P', '1080P'],
      size: '1.4 GB',
      storyline:
          'Top IAF aviators come together in the face of imminent danger to form Air Dragons, giving their all for the country whilst going through emotional highs and lows.',
      poster: 'https://m.media-amazon.com/images/M/MV5BM2M0YzQyOTktMjkzYS00YjVlLWI5YjktN2FjMDliMjg1Y2U1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      screenshots: [
        'https://m.media-amazon.com/images/M/MV5BM2M0YzQyOTktMjkzYS00YjVlLWI5YjktN2FjMDliMjg1Y2U1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ],
      categories: [
        const MovieCategory(id: 3, name: 'Bollywood', slug: 'bollywood'),
        const MovieCategory(id: 10, name: 'Hindi', slug: 'hindi'),
        const MovieCategory(id: 0, name: 'Action', slug: 'action'),
      ],
      downloadLinks: [
        DownloadLink(
          title: 'Download 480p [500MB] - Direct Cloud',
          url: 'https://hubcloud.club/drive/fighter-480p-hindi',
          quality: '480P',
          size: '500MB',
        ),
        DownloadLink(
          title: 'Download 720p [1.2GB] - Fast Server',
          url: 'https://hubcloud.club/drive/fighter-720p-hindi',
          quality: '720P',
          size: '1.2GB',
        ),
        DownloadLink(
          title: 'Download 1080p [2.5GB] - Ultra HD',
          url: 'https://hubcloud.club/drive/fighter-1080p-hindi',
          quality: '1080P',
          size: '2.5GB',
        ),
      ],
      date: '2024-03-21T09:00:00',
    ),
    Movie(
      id: 1005,
      slug: 'dune-part-two-2024',
      title: 'Dune: Part Two',
      rawTitle: 'Dune Part Two (2024) Dual Audio Hindi ORG + English 720p 1080p BluRay',
      year: '2024',
      rating: '8.6',
      languages: ['Hindi', 'English'],
      qualities: ['720P', '1080P', '4K'],
      size: '2.2 GB',
      storyline:
          'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
      poster: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
      screenshots: [
        'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
      ],
      categories: [
        const MovieCategory(id: 4, name: 'Hollywood', slug: 'hollywood'),
        const MovieCategory(id: 1, name: 'Dual Audio', slug: 'dual-audio'),
        const MovieCategory(id: 0, name: 'Sci-Fi & Fantasy', slug: 'sci-fi-fantasy'),
      ],
      downloadLinks: [
        DownloadLink(
          title: 'Download 720p [1.4GB] - Direct Cloud',
          url: 'https://hubcloud.club/drive/dune2-720p-dual',
          quality: '720P',
          size: '1.4GB',
        ),
        DownloadLink(
          title: 'Download 1080p [3.1GB] - Ultra HD',
          url: 'https://hubcloud.club/drive/dune2-1080p-dual',
          quality: '1080P',
          size: '3.1GB',
        ),
      ],
      date: '2024-04-16T18:45:00',
    ),
    Movie(
      id: 1006,
      slug: 'animal-2023-hindi',
      title: 'Animal',
      rawTitle: 'Animal (2023) Hindi 480p 720p 1080p WEB-DL Clean Audio',
      year: '2023',
      rating: '6.8',
      languages: ['Hindi'],
      qualities: ['480P', '720P', '1080P'],
      size: '1.7 GB',
      storyline:
          'A father-son bond carved in blood. Ranvijay sets out on a ruthless path of vengeance across the globe when an assassination attempt is made on his father.',
      poster: 'https://m.media-amazon.com/images/M/MV5BNGViM2M4NmUtMmNkNy00MTU5LWIyYzgtYDA2NzFiZGU4MzVkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      screenshots: [
        'https://m.media-amazon.com/images/M/MV5BNGViM2M4NmUtMmNkNy00MTU5LWIyYzgtYDA2NzFiZGU4MzVkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ],
      categories: [
        const MovieCategory(id: 3, name: 'Bollywood', slug: 'bollywood'),
        const MovieCategory(id: 10, name: 'Hindi', slug: 'hindi'),
        const MovieCategory(id: 0, name: 'Action', slug: 'action'),
      ],
      downloadLinks: [
        DownloadLink(
          title: 'Download 480p [600MB] - Direct Cloud',
          url: 'https://hubcloud.club/drive/animal-480p-hindi',
          quality: '480P',
          size: '600MB',
        ),
        DownloadLink(
          title: 'Download 720p [1.5GB] - Fast Server',
          url: 'https://hubcloud.club/drive/animal-720p-hindi',
          quality: '720P',
          size: '1.5GB',
        ),
        DownloadLink(
          title: 'Download 1080p [3.0GB] - Ultra HD',
          url: 'https://hubcloud.club/drive/animal-1080p-hindi',
          quality: '1080P',
          size: '3.0GB',
        ),
      ],
      date: '2024-01-26T08:30:00',
    ),
    Movie(
      id: 1007,
      slug: 'mirzapur-season-3',
      title: 'Mirzapur (Season 3)',
      rawTitle: 'Mirzapur Season 3 Complete Hindi [All Episodes] 720p 1080p WEB Series',
      year: '2024',
      rating: '8.5',
      languages: ['Hindi'],
      qualities: ['720P', '1080P'],
      size: '3.5 GB',
      storyline:
          'Guddu and Golu stake their claim to the throne of Mirzapur while Kaleen Bhaiya plots his ultimate resurgence in the heartland of Purvanchal.',
      poster: 'https://m.media-amazon.com/images/M/MV5BZDU5ZGYzZTYtMTZhYS00MjY1LWE4MmItYmI2M2RkOTYwZWE2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      screenshots: [
        'https://m.media-amazon.com/images/M/MV5BZDU5ZGYzZTYtMTZhYS00MjY1LWE4MmItYmI2M2RkOTYwZWE2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ],
      categories: [
        const MovieCategory(id: 6, name: 'Web Series', slug: 'web-series'),
        const MovieCategory(id: 10, name: 'Hindi', slug: 'hindi'),
        const MovieCategory(id: 0, name: 'Drama', slug: 'drama'),
      ],
      downloadLinks: [
        DownloadLink(
          title: 'Download All Episodes 720p [2.8GB] - Fast Server',
          url: 'https://hubcloud.club/drive/mirzapur-s3-720p',
          quality: '720P',
          size: '2.8GB',
        ),
        DownloadLink(
          title: 'Download All Episodes 1080p [5.5GB] - Ultra HD',
          url: 'https://hubcloud.club/drive/mirzapur-s3-1080p',
          quality: '1080P',
          size: '5.5GB',
        ),
      ],
      date: '2024-07-05T00:00:00',
    ),
    Movie(
      id: 1008,
      slug: '12th-fail-2023',
      title: '12th Fail',
      rawTitle: '12th Fail (2023) Hindi 480p 720p 1080p WEB-DL Full Movie',
      year: '2023',
      rating: '8.9',
      languages: ['Hindi'],
      qualities: ['480P', '720P', '1080P'],
      size: '1.2 GB',
      storyline:
          'Inspired by real-life events, Manoj Kumar Sharma from Chambal overcomes extreme poverty, academic setbacks, and relentless struggles to crack the prestigious UPSC exam.',
      poster: 'https://m.media-amazon.com/images/M/MV5BOTU2NWVmMzYtNDVjMC00NWY2LWFmZTUtYzg2MGNhZGUzYmM2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      screenshots: [
        'https://m.media-amazon.com/images/M/MV5BOTU2NWVmMzYtNDVjMC00NWY2LWFmZTUtYzg2MGNhZGUzYmM2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ],
      categories: [
        const MovieCategory(id: 3, name: 'Bollywood', slug: 'bollywood'),
        const MovieCategory(id: 10, name: 'Hindi', slug: 'hindi'),
        const MovieCategory(id: 0, name: 'Drama', slug: 'drama'),
      ],
      downloadLinks: [
        DownloadLink(
          title: 'Download 720p [1.1GB] - Direct Cloud',
          url: 'https://hubcloud.club/drive/12thfail-720p-hindi',
          quality: '720P',
          size: '1.1GB',
        ),
        DownloadLink(
          title: 'Download 1080p [2.2GB] - Ultra HD',
          url: 'https://hubcloud.club/drive/12thfail-1080p-hindi',
          quality: '1080P',
          size: '2.2GB',
        ),
      ],
      date: '2023-12-29T11:00:00',
    ),
    Movie(
      id: 1009,
      slug: 'salaar-part-1-ceasefire-2023',
      title: 'Salaar: Part 1 – Ceasefire',
      rawTitle: 'Salaar (2023) Multi Audio [Hindi + Telugu] 480p 720p 1080p HDRip',
      year: '2023',
      rating: '7.5',
      languages: ['Hindi', 'Telugu', 'Tamil', 'Kannada'],
      qualities: ['480P', '720P', '1080P'],
      size: '1.6 GB',
      storyline:
          'In the violent dystopian city-state of Khansaar, Deva returns from exile to help his childhood friend Varadha secure his rightful place as the ruler.',
      poster: 'https://m.media-amazon.com/images/M/MV5BMmU1YWU1MmMtMTNkMy00OGZmLTgwOWYtNjc5NmVkMDFmNTM2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      screenshots: [
        'https://m.media-amazon.com/images/M/MV5BMmU1YWU1MmMtMTNkMy00OGZmLTgwOWYtNjc5NmVkMDFmNTM2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ],
      categories: [
        const MovieCategory(id: 5, name: 'South Indian', slug: 'south-indian'),
        const MovieCategory(id: 1, name: 'Dual Audio', slug: 'dual-audio'),
        const MovieCategory(id: 0, name: 'Action', slug: 'action'),
      ],
      downloadLinks: [
        DownloadLink(
          title: 'Download 720p [1.4GB] - Direct Cloud',
          url: 'https://hubcloud.club/drive/salaar-720p-multi',
          quality: '720P',
          size: '1.4GB',
        ),
        DownloadLink(
          title: 'Download 1080p [2.9GB] - Ultra HD',
          url: 'https://hubcloud.club/drive/salaar-1080p-multi',
          quality: '1080P',
          size: '2.9GB',
        ),
      ],
      date: '2024-01-20T16:20:00',
    ),
    Movie(
      id: 1010,
      slug: 'panchayat-season-3',
      title: 'Panchayat (Season 3)',
      rawTitle: 'Panchayat Season 3 Complete Hindi WEB-DL 720p 1080p',
      year: '2024',
      rating: '8.9',
      languages: ['Hindi'],
      qualities: ['720P', '1080P'],
      size: '2.1 GB',
      storyline:
          'Abhishek Tripathi tackles local elections, village politics, and administrative rivalries in the quirky village of Phulera.',
      poster: 'https://m.media-amazon.com/images/M/MV5BMjY5ZGE1N2ItMjA1Zi00YmY5LWI4NGEtNmQzYWMzOWExYTFmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      screenshots: [
        'https://m.media-amazon.com/images/M/MV5BMjY5ZGE1N2ItMjA1Zi00YmY5LWI4NGEtNmQzYWMzOWExYTFmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ],
      categories: [
        const MovieCategory(id: 6, name: 'Web Series', slug: 'web-series'),
        const MovieCategory(id: 10, name: 'Hindi', slug: 'hindi'),
        const MovieCategory(id: 0, name: 'Comedy', slug: 'comedy'),
      ],
      downloadLinks: [
        DownloadLink(
          title: 'Download All Episodes 720p [1.8GB] - Fast Server',
          url: 'https://hubcloud.club/drive/panchayat-s3-720p',
          quality: '720P',
          size: '1.8GB',
        ),
      ],
      date: '2024-05-28T05:00:00',
    ),
    Movie(
      id: 1011,
      slug: 'jawan-2023-hindi',
      title: 'Jawan',
      rawTitle: 'Jawan (2023) Extended Cut Hindi 480p 720p 1080p HDRip',
      year: '2023',
      rating: '7.4',
      languages: ['Hindi', 'Tamil', 'Telugu'],
      qualities: ['480P', '720P', '1080P', '4K'],
      size: '1.5 GB',
      storyline:
          'A prison warden driven by a personal vendetta recruits inmates to commit outrageous acts of vigilante justice to right the wrongs of society.',
      poster: 'https://m.media-amazon.com/images/M/MV5BN2E1ZWI1NzUtOTk4OC00YzQ4LThjYmQtODhjNWU3OWEzODFkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      screenshots: [
        'https://m.media-amazon.com/images/M/MV5BN2E1ZWI1NzUtOTk4OC00YzQ4LThjYmQtODhjNWU3OWEzODFkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ],
      categories: [
        const MovieCategory(id: 3, name: 'Bollywood', slug: 'bollywood'),
        const MovieCategory(id: 10, name: 'Hindi', slug: 'hindi'),
        const MovieCategory(id: 0, name: 'Action', slug: 'action'),
      ],
      downloadLinks: [
        DownloadLink(
          title: 'Download 480p [500MB] - Direct Cloud',
          url: 'https://hubcloud.club/drive/jawan-480p-hindi',
          quality: '480P',
          size: '500MB',
        ),
        DownloadLink(
          title: 'Download 720p [1.3GB] - Fast Server',
          url: 'https://hubcloud.club/drive/jawan-720p-hindi',
          quality: '720P',
          size: '1.3GB',
        ),
        DownloadLink(
          title: 'Download 1080p [2.6GB] - Ultra HD',
          url: 'https://hubcloud.club/drive/jawan-1080p-hindi',
          quality: '1080P',
          size: '2.6GB',
        ),
      ],
      date: '2023-11-02T10:00:00',
    ),
    Movie(
      id: 1012,
      slug: 'oppenheimer-2023',
      title: 'Oppenheimer',
      rawTitle: 'Oppenheimer (2023) Dual Audio [Hindi + English] 720p 1080p BluRay',
      year: '2023',
      rating: '8.9',
      languages: ['Hindi', 'English'],
      qualities: ['720P', '1080P', '4K'],
      size: '2.5 GB',
      storyline:
          'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during the Manhattan Project.',
      poster: 'https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      screenshots: [
        'https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      ],
      categories: [
        const MovieCategory(id: 4, name: 'Hollywood', slug: 'hollywood'),
        const MovieCategory(id: 1, name: 'Dual Audio', slug: 'dual-audio'),
        const MovieCategory(id: 0, name: 'Drama', slug: 'drama'),
      ],
      downloadLinks: [
        DownloadLink(
          title: 'Download 720p [1.6GB] - Direct Cloud',
          url: 'https://hubcloud.club/drive/oppenheimer-720p-dual',
          quality: '720P',
          size: '1.6GB',
        ),
        DownloadLink(
          title: 'Download 1080p [3.4GB] - Ultra HD',
          url: 'https://hubcloud.club/drive/oppenheimer-1080p-dual',
          quality: '1080P',
          size: '3.4GB',
        ),
      ],
      date: '2023-11-21T14:00:00',
    ),
  ];
}
